GYF/Controllers/AdminReportsController.cs
using GYF.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GYF.Filter;
using System.IO;

using System.Data;

namespace GYF.Controllers
{
    public class AdminReportsController : AdminBaseController
    {
        public ActionResult GetStateCityByPincode(string PinCode)
        {
            AdminReports model = new AdminReports();
            try
            {

                model.PinCode = PinCode;



                DataSet ds = model.GetStateCityByPincode();

                if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
                {

                    model.State = ds.Tables[0].Rows[0]["StateName"].ToString();
                    model.City = ds.Tables[0].Rows[0]["CityName"].ToString();
                    model.Result = "Yes";
                }

            }
            catch (Exception ex)
            {

            }
            return Json(model, JsonRequestBehavior.AllowGet);
        }
        // GET: AdminReports
        public ActionResult AssociateList(AdminReports model)
        {
            List<AdminReports> list = new List<AdminReports>();
            DataSet ds = model.GettingAssociateList();
            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow r in ds.Tables[0].Rows)
                {
                    AdminReports obj = new AdminReports();
                    obj.Password = Crypto.Decrypt(r["Password"].ToString());
                    obj.LoginId = r["LoginId"].ToString();
                    obj.Name = r["Name"].ToString();
                    obj.Mobile = r["Mobile"].ToString();
                    obj.Email = r["Email"].ToString();
                    obj.SponsorID = r["SponsorId"].ToString();
                    obj.SponsorName = r["SponsorName"].ToString();
                    obj.Fk_UserId = r["PK_UserId"].ToString();
                    obj.IsBlocked = r["IsBlocked"].ToString();
                    obj.PermanentDate = r["PermanentDate"].ToString();
                    list.Add(obj);
                }
                model.AssociateList = list;
            }
            return View(model);
        }

        [HttpPost]
        [OnAction(ButtonName = "btnDetails")]
        [ActionName("AssociateList")]
        public ActionResult FilterAssociateList(AdminReports model)
        {
            List<AdminReports> list = new List<AdminReports>();
            model.LoginId = model.LoginId;
            model.FromDate = string.IsNullOrEmpty(model.FromDate) ? null : Common.ConvertToSystemDate(model.FromDate, "dd/MM/yyyy");
            model.ToDate = string.IsNullOrEmpty(model.ToDate) ? null : Common.ConvertToSystemDate(model.ToDate, "dd/MM/yyyy");
            DataSet ds = model.GettingAssociateList();
            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow r in ds.Tables[0].Rows)
                {
                    AdminReports obj = new AdminReports();
                    obj.Password = Crypto.Decrypt(r["Password"].ToString());
                    obj.LoginId = r["LoginId"].ToString();
                    obj.Name = r["Name"].ToString();
                    obj.Mobile = r["Mobile"].ToString();
                    obj.Email = r["Email"].ToString();
                    obj.SponsorID = r["SponsorId"].ToString();
                    obj.SponsorName = r["SponsorName"].ToString();
                    obj.Fk_UserId = r["PK_UserId"].ToString();
                    obj.IsBlocked = r["IsBlocked"].ToString();
                    list.Add(obj);
                }
                model.AssociateList = list;
            }
            return View(model);
        }

        public ActionResult BlockAssociate(string Fk_UserId)
        {
            AdminReports model = new AdminReports();
            model.Fk_UserId = Fk_UserId;
            model.UpdatedBy = Session["Pk_AdminId"].ToString();
            DataSet ds = model.BlockUser();
            if (ds != null && ds.Tables.Count > 0)
            {
                if (ds.Tables[0].Rows[0]["Msg"].ToString() == "1")
                {
                    TempData["AssociateList"] = "Associate Blocked";
                }
                else if (ds.Tables[0].Rows[0]["Msg"].ToString() == "0")
                {
                    TempData["AssociateList"] = ds.Tables[0].Rows[0]["ErrorMessage"].ToString();
                }
            }
            return RedirectToAction("AssociateList");
        }

        public ActionResult UnBlockAssociate(string Fk_UserId)
        {
            AdminReports model = new AdminReports();
            model.Fk_UserId = Fk_UserId;
            model.UpdatedBy = Session["Pk_AdminId"].ToString();
            DataSet ds = model.UnBlockUser();
            if (ds != null && ds.Tables.Count > 0)
            {
                if (ds.Tables[0].Rows[0]["Msg"].ToString() == "1")
                {
                    TempData["AssociateList"] = "Associate UnBlocked";
                }
                else if (ds.Tables[0].Rows[0]["Msg"].ToString() == "0")
                {
                    TempData["AssociateList"] = ds.Tables[0].Rows[0]["ErrorMessage"].ToString();
                }
            }
            return RedirectToAction("AssociateList");
        }

        public ActionResult AssociateProfile(string Fk_UserId)
        {
            AdminReports model = new AdminReports();
            model.Fk_UserId = Fk_UserId;
            DataSet ds = model.GettingProfile();
            if (ds != null && ds.Tables.Count > 0)
            {
                model.LoginId = ds.Tables[0].Rows[0]["LoginId"].ToString();
                model.Name = ds.Tables[0].Rows[0]["Name"].ToString();
                model.Mobile = ds.Tables[0].Rows[0]["Mobile"].ToString();
                model.SponsorID = ds.Tables[0].Rows[0]["SponsorId"].ToString();
                model.SponsorName = ds.Tables[0].Rows[0]["SponsorName"].ToString();
                model.BankName = ds.Tables[0].Rows[0]["BankName"].ToString();
                model.BankHolderName = ds.Tables[0].Rows[0]["BankHolderName"].ToString();
                model.AccountNo = ds.Tables[0].Rows[0]["AccountNo"].ToString();
                model.IFSC = ds.Tables[0].Rows[0]["IFSC"].ToString();
                model.BankBranch = ds.Tables[0].Rows[0]["BankBranch"].ToString();
                model.Address = ds.Tables[0].Rows[0]["Address"].ToString();
                model.PinCode = ds.Tables[0].Rows[0]["PinCode"].ToString();
                model.State = ds.Tables[0].Rows[0]["State"].ToString();
                model.City = ds.Tables[0].Rows[0]["City"].ToString();
                model.PanNumber = ds.Tables[0].Rows[0]["PanNumber"].ToString();
                model.PAYTMNo = ds.Tables[0].Rows[0]["PAYTMNo"].ToString();
                model.Phonepay = ds.Tables[0].Rows[0]["Phonepay"].ToString();
                model.GooglePay = ds.Tables[0].Rows[0]["GooglePay"].ToString();
                model.NomineName = ds.Tables[0].Rows[0]["NomineName"].ToString();
                model.NomineRealation = ds.Tables[0].Rows[0]["NomineRealation"].ToString();
                model.Fk_UserId = ds.Tables[0].Rows[0]["PK_UserId"].ToString();
                model.Email = ds.Tables[0].Rows[0]["Email"].ToString();
                model.FirstName = ds.Tables[0].Rows[0]["FirstName"].ToString();
                model.LastName = ds.Tables[0].Rows[0]["LastName"].ToString();
                model.DOB = ds.Tables[0].Rows[0]["DOB"].ToString();
            }
            return View(model);
        }

        [HttpPost]
        [OnAction(ButtonName = "btnUpdateProfile")]
        [ActionName("AssociateProfile")]
        public ActionResult UpdateAssociateProfile(AdminReports model, IEnumerable<HttpPostedFileBase> Image)
        {
            model.Fk_UserId = model.Fk_UserId;
            model.UpdatedBy = Session["Pk_AdminId"].ToString();
            try
            {
                foreach (var file in Image)
                {
                    if (file != null && file.ContentLength > 0)
                    {

                        model.ProfilePic = "../AssociatePic/" + Guid.NewGuid() + Path.GetExtension(file.FileName);
                        file.SaveAs(Path.Combine(Server.MapPath(model.ProfilePic)));
                    }
                }
                model.DOB = string.IsNullOrEmpty(model.DOB) ? null : Common.ConvertToSystemDate(model.DOB, "dd/MM/yyyy");
                DataSet ds = model.UpdatingProfile();
                if (ds != null && ds.Tables.Count > 0)
                {
                    if (ds.Tables[0].Rows[0]["Msg"].ToString() == "1")
                    {
                        TempData["AssociateList"] = "Profile Updated Successfully";
                    }
                    else if (ds.Tables[0].Rows[0]["Msg"].ToString() == "0")
                    {
                        TempData["UpdateProfile"] = ds.Tables[0].Rows[0]["ErrorMessage"].ToString();
                        return View(model);
                    }
                }
            }
            catch (Exception ex)
            {
                TempData["UpdateProfile"] = ex.Message;
                return View(model);
            }


            return RedirectToAction("AssociateList");
        }


        public ActionResult DirectReport(AdminReports model)

        {
            return View(model);
        }



        [HttpPost]
        [OnAction(ButtonName = "GetDirect")]
        [ActionName("DirectReport")]
        public ActionResult GetDirectList(AdminReports model)
        {
            List<AdminReports> list = new List<AdminReports>();
            model.LoginId = model.LoginId;
            DataSet ds = model.GetDirectList();
            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow r in ds.Tables[0].Rows)

GYF/Views/AdminReports/AssociateList.cshtml
@model GYF.Models.AdminReports

@{
    ViewBag.Title = "AssociateList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("AssociateList", "AdminReports", FormMethod.Post, new { @id = "form3", enctype = "multipart/form-data" }))
{
      <!-- Page header -->
    <div class="page-header page-header-light">
        <div class="page-header-content header-elements-md-inline">
            <div class="page-title d-flex">
                <h4><i class="icon-arrow-left52 mr-2"></i> <span class="font-weight-semibold">Admin Reports </span> - Associate List</h4>
                <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
            </div>
        </div>
    </div>
    <!-- /page header -->

    <div class="content">

        <div class="row">
            <div class="col-xl-12">
                <!-- Marketing campaigns -->
                <div class="card">
                    <div class="card-header header-elements-sm-inline">
                        <h6 class="card-title">Associate List</h6>
                        <p style="color:red">
                            @TempData["AssociateList"]
                        </p>
                    </div>
                    <div class="card-body">
                        <div class="row justify-content-center">
                            <div class="col-md-12 mx-auto">
                                <div class="row ">
                                    <div class="col-lg-3 col-md-3">
                                        <div class="form-group">
                                            <label>
                                                Login Id
                                            </label>
                                            @Html.TextBoxFor(m => m.LoginId, new { @class = "form-control", @Placeholder = "Login Id", @onchange = "getLoggerName();" })

                                        </div>
                                    </div>
                                    <div class="col-lg-3 col-md-3">
                                        <div class="form-group">
                                            <label> Name</label>
                                            @Html.TextBoxFor(m => m.Name, new { @class = "form-control", @Placeholder = "Name", @readonly = "readonly" })

                                        </div>
                                    </div>
                                    <div class="col-lg-3 col-md-3">
                                        <div class="form-group ">
                                            <label> From Date</label>
                                            @Html.TextBoxFor(m => m.FromDate, new { @class = "form-control", @readonly = "readonly" })

                                        </div>
                                    </div>
                                    <div class="col-lg-3 col-md-3">
                                        <div class="form-group ">
                                            <label> To Date </label>
                                            @Html.TextBoxFor(m => m.ToDate, new { @class = "form-control", @readonly = "readonly" })
                                        </div>
                                    </div>
                                    <div class="col-lg-3 col-md-3">
                                        <div class="form-group ">
                                            <input type="submit" class="btn btn-info" name="btnDetails" id="btnDetails" style="margin-top:25px" value="Get Details" />
                                        </div>
                                    </div>
                                </div>


                            </div>
                        </div>

                    </div>
                    <div class="table-responsive">
                        <table class="table table-bordered w-100 mb-0" id="example24">
                            <thead>
                                <tr>

                                    <th>Sr No.</th>
                                    <th>Login ID</th>
                                    <th>Password</th>
                                    <th>Name</th>
                                    <th>Mobile</th>
                                    <th>Sponsor Id</th>
                                    <th>Sponsor Name</th>
                                    <th>Active Date</th>
                                    <th>Email</th>
                                    <th>Block/UnBlock</th>
                                    <th>Action</th>

                                </tr>

                            </thead>
                            <tbody>
                                @if (Model != null)
                                {
                                    if (Model.AssociateList != null)
                                    {
                                        int i = 1;
                                        foreach (var Item in Model.AssociateList)
                                        {
                                            <tr class="text-left">

                                                <td>
                                                    @i
                                                    @Html.HiddenFor(m => m.Fk_UserId)
                                                </td>
                                                <td>@Item.LoginId</td>
                                                <td>@Item.Password</td>
                                                <td>@Item.Name</td>
                                                <td>@Item.Mobile</td>
                                                <td>@Item.SponsorID</td>
                                                <td>@Item.SponsorName</td>
                                                <td>@Item.PermanentDate</td>
                                                <td>@Item.Email</td>
                                                <td>
                                                    @if (Item.Fk_UserId != "1" && Item.IsBlocked == "False")
                                                    {

                                                        <a href="/AdminReports/BlockAssociate?Fk_UserId=@Item.Fk_UserId" onclick="return confirm('Are you sure you want to Block this Associate?');" class="btn btn-sm btn-success">Block</a>

                                                    }
                                                    else if (Item.Fk_UserId != "1")
                                                    {
                                                        <a href="/AdminReports/UnBlockAssociate?Fk_UserId=@Item.Fk_UserId" onclick="return confirm('Are you sure you want to Un Block this item?');"class="btn btn-sm btn-danger">UnBlock</a>
                                                    }
                                                </td>

                                                <td>
                                                    <a href="/AdminReports/AssociateProfile?Fk_UserId=@Item.Fk_UserId" class="btn btn-sm btn-primary">Edit</a>

                                                </td>
                                            </tr>
                                            i++;
                                        }

                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<script>


    function getLoggerName() {
        var LoginId = $('#LoginId');
        $.ajax({
            url: '/Admin/getLoggerName',
            data: {
                'LoginId': $('#LoginId').val()
            },
            type: 'GET',
            dataType: 'JSON',
            success: function (data) {
                if (data.Name == null) {
                    alert('Invalid Login ID')
                    $("#LoginId").val('');
                    $("#Name").val('');
                    return false;
                }
                $("#Name").val(data.Name);

            }
        });
    }


    $('#FromDate').datepicker({
        dateFormat: 'dd/mm/yy',
        changeMonth: true,
        changeYear: true,
        yearRange: '1950:2020'
    });

    $('#ToDate').datepicker({
        dateFormat: 'dd/mm/yy',
        changeMonth: true,
        changeYear: true,
        yearRange: '1950:2020'
    });
</script>

GYF/Views/AdminReports/DirectIncome.cshtml
@model GYF.Models.AdminReports

@{
    ViewBag.Title = "DirectIncome";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("DirectIncome", "AdminReports", FormMethod.Post, new { id = "form" }))
{

    <!-- Page header -->
    <div class="page-header page-header-light">
        <div class="page-header-content header-elements-md-inline">
            <div class="page-title d-flex">
                <h4><i class="icon-arrow-left52 mr-2"></i> <span class="font-weight-semibold">Income Reports</span> - Direct Income</h4>
                <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
            </div>
        </div>
    </div>
    <!-- /page header -->

    <div class="content">

        <div class="row">
            <div class="col-xl-12">
                <!-- Marketing campaigns -->
                <div class="card">
                    <div class="card-header header-elements-sm-inline">
                        <h6 class="card-title">Direct Income</h6>

                    </div>
                    <div class="card-header">

                        <p style="color: red">
                            @TempData["DirectIncome"]
                        </p>
                    </div><div class="card-body">
                        <div class="row justify-content-center">
                            <div class="col-md-12 mx-auto">
                                <div class="row ">
                                    <div class="col-lg-3 col-md-3">
                                        <div class="form-group">
                                            <label>
                                                Login Id
                                            </label>
                                            @Html.TextBoxFor(m => m.LoginId, new { @class = "form-control", @Placeholder = "Login Id", @onchange = "getLoggerName();" })

                                        </div>
                                    </div>
                                    <div class="col-lg-3 col-md-3">
                                        <div class="form-group">
                                            <label> Name</label>
                                            @Html.TextBoxFor(m => m.Name, new { @class = "form-control", @Placeholder = "Name", @readonly = "readonly" })

                                        </div>
                                    </div>
                                    <div class="col-lg-3 col-md-3">
                                        <div class="form-group ">
                                            <label> From Date</label>
                                            @Html.TextBoxFor(m => m.FromDate, new { @class = "form-control", @readonly = "readonly" })

                                        </div>
                                    </div>
                                    <div class="col-lg-3 col-md-3">
                                        <div class="form-group ">
                                            <label> To Date </label>
                                            @Html.TextBoxFor(m => m.ToDate, new { @class = "form-control", @readonly = "readonly" })
                                        </div>
                                    </div>
                                    <div class="col-lg-3 col-md-3">
                                        <div class="form-group ">
                                            <input type="submit" class="btn btn-info" name="btnDetails" id="btnDetails" style="margin-top:25px" value="Get Details" />
                                        </div>
                                    </div>
                                </div>


                            </div>
                        </div>

                    </div>
                    <div class="table-responsive">
                        <table class="table table-bordered w-100 mb-0" id="example24">
                            <thead>
                                <tr>

                                    <th>Sr No.</th>
                                    <th>Date</th>
                                    <th>From Id</th>
                                    <th>Direct Income</th>
                                    <th>Status</th>

                                </tr>

                            </thead>
                            <tbody>
                                @if (Model != null)
                                {
                                    if (Model.DirectIncomeList != null)
                                    {
                                        int i = 1;
                                        foreach (var Item in Model.DirectIncomeList)
                                        {
                                            <tr class="text-left">

                                                <td>
                                                    @i

                                                </td>
                                                <td>@Item.CurrentDate</td>
                                                <td>@Item.FromId</td>
                                                <td>@Item.Amount</td>
                                                <td>@Item.Status</td>



                                            </tr>
                                            i++;
                                        }

                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

}

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<script>

    function getLoggerName() {
        var LoginId = $('#LoginId');
        $.ajax({
            url: '/Admin/getLoggerName',
            data: {
                'LoginId': $('#LoginId').val()
            },
            type: 'GET',
            dataType: 'JSON',
            success: function (data) {
                if (data.Name == null) {
                    alert('Invalid Login ID')
                    $("#LoginId").val('');
                    $("#Name").val('');
                    return;
                }
                $("#Name").val(data.Name);

            }
        });
    }

    $('#FromDate').datepicker({
        dateFormat: 'dd/mm/yy',
        changeMonth: true,
        changeYear: true,
        yearRange: '1950:2020'
    });

    $('#ToDate').datepicker({
        dateFormat: 'dd/mm/yy',
        changeMonth: true,
        changeYear: true,
        yearRange: '1950:2020'
    });
</script>

GYF/Views/AdminReports/DirectReport.cshtml
@model GYF.Models.AdminReports

@{
    ViewBag.Title = "DirectReport";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("DirectReport", "AdminReports", FormMethod.Post, new { @id = "form3", enctype = "multipart/form-data" }))
{
    <div class="page-header page-header-light">
        <div class="page-header-content header-elements-md-inline">
            <div class="page-title d-flex">
                <h4><i class="icon-arrow-left52 mr-2"></i> <span class="font-weight-semibold">Team </span> - Direct</h4>
                <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
            </div>
        </div>
    </div>
    <!-- /page header -->

    <div class="content">

        <div class="row">
            <div class="col-xl-12">
                <!-- Marketing campaigns -->
                <div class="card">
                    <div class="card-header header-elements-sm-inline">
                        <h6 class="card-title">Direct</h6>
                        <p style="color:red">
                            @TempData["DirectReport"]
                        </p>
                    </div>
                    <div class="card-body">
                        <div class="row justify-content-center">
                            <div class="col-md-12 mx-auto">
                                <div class="row ">

                                    <div class="col-lg-3 col-md-3">
                                        <div class="form-group ">
                                            <label> Login Id <span style="color: red">*</span></label>
                                            @Html.TextBoxFor(m => m.LoginId, new { @class = "form-control" })

                                        </div>
                                    </div>
                                    <div class="col-lg-3 col-md-3">
                                        <div class="form-group ">
                                            <input type="submit" class="btn btn-info" name="GetDirect" id="GetDirect" onclick="return validate();" style="margin-top:25px" value="Get Direct" />
                                        </div>
                                    </div>
                                </div>


                            </div>
                        </div>

                    </div>
                    <div class="table-responsive">
                        <table class="table table-bordered w-100 mb-0" id="example24">
                            <thead>
                                <tr>

                                    <th>Sr No.</th>
                                    <th>Login Id</th>
                                    <th>Name</th>
                                    <th>Joining Date</th>
                                    <th>Active Date</th>
                                    <th>Mobile</th>

                                </tr>

                            </thead>
                            <tbody>
                                @if (Model != null)
                                {
                                    if (Model.DirectReportList != null)
                                    {
                                        int i = 1;
                                        foreach (var Item in Model.DirectReportList)
                                        {
                                            <tr class="text-left">

                                                <td>
                                                    @i
                                                </td>
                                                <td>@Item.LoginId</td>
                                                <td>@Item.Name</td>
                                                <td>@Item.JoiningDate</td>
                                                <td>@Item.PermanentDate</td>
                                                <td>@Item.Mobile</td>

                                            </tr>
                                            i++;
                                        }

                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
        </div>
    </div>

}

<script>
    function validate() {
        $(".errortext").removeClass('errortext');
        if ($("#LoginId").val() == '') {
            $("#LoginId").addClass('errortext');
            $("#LoginId").focus();
            return false;
        }
    }
</script>