GYF/Controllers/AssociateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GYF.Models;
using GYF.Filter;
using System.Data;
using System.IO;
using BusinessLayer;
using System.Net.Mail;
using System.Net;

namespace GYF.Controllers
{
    public class AssociateController : AssociateBaseController
    {
        // GET: Associate
        public ActionResult AssociateDashBoard(DashBoard model)
        {
            List<DashBoard> list = new List<DashBoard>();
            List<DashBoard> list1 = new List<DashBoard>();
            model.Fk_UserId = Session["Pk_userId"].ToString();
            DataSet ds = model.GetDashboardDetails();


            //   ViewBag.TotalDirect = ds.Tables[1].Rows[0]["TotalDirect"].ToString();
            ViewBag.TotalROI = ds.Tables[1].Rows[0]["TotalROI"].ToString();
            ViewBag.TotalActiveDirect = ds.Tables[1].Rows[0]["TotalActiveDirect"].ToString();
            ViewBag.TotalTeam = ds.Tables[1].Rows[0]["TotalTeam"].ToString();
            ViewBag.TotalActiveSingleLegTeam = ds.Tables[1].Rows[0]["TotalActiveSingleLegTeam"].ToString();

            ViewBag.TotalDirectIncome = ds.Tables[1].Rows[0]["TotalDirectIncome"].ToString();
            ViewBag.TotalSingleLegIncome = ds.Tables[1].Rows[0]["TotalSingleLegIncome"].ToString();
            ViewBag.SingleLegRank = ds.Tables[1].Rows[0]["SingleLegRank"].ToString();
            ViewBag.GrandTotalIncome = ds.Tables[1].Rows[0]["GrandTotalIncome"].ToString();

            if (ViewBag.SingleLegRank == "")
            {
                ViewBag.SingleLegRank = "0";
            }
            ViewBag.TotalLevelIncome = ds.Tables[1].Rows[0]["TotalLevelIncome"].ToString();
            ViewBag.TotalPoolIncome = ds.Tables[1].Rows[0]["TotalPoolIncome"].ToString();
            ViewBag.CurrentIncome = ds.Tables[1].Rows[0]["CurrentIncome"].ToString();
            ViewBag.BankWithdrawal = ds.Tables[1].Rows[0]["BankWithdraw"].ToString();
            ViewBag.MyReward = ds.Tables[1].Rows[0]["MyReward"].ToString();
            //    ViewBag.WalletBalance = ds.Tables[1].Rows[0]["WalletBalance"].ToString();
            //ViewBag.TotalJoinings = ds.Tables[1].Rows[0]["TotalJoinings"].ToString();
            //ViewBag.TodayJoinings = ds.Tables[1].Rows[0]["TodayJoinings"].ToString();

            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow r in ds.Tables[0].Rows)
                {
                    DashBoard obj = new DashBoard();
                    obj.LoginId = r["LoginId"].ToString();
                    obj.Name = r["Name"].ToString();
                    obj.JoiningDate = r["JoiningDate"].ToString();
                    obj.PermanentDate = r["PermanentDate"].ToString();
                    obj.Package = r["Package"].ToString();
                    obj.Status = r["Status"].ToString();
                    list.Add(obj);
                }
                model.DashboardList = list;
            }


            if (ds != null && ds.Tables.Count > 0 && ds.Tables[2].Rows.Count > 0)
            {
                foreach (DataRow r in ds.Tables[2].Rows)
                {
                    DashBoard obj1 = new DashBoard();
                    //  obj1.pk_singlelegIncomeId = r["pk_singlelegIncomeId"].ToString();
                    obj1.Rank = r["RankName"].ToString();
                    obj1.TargetTeam = r["TargetTeam"].ToString();
                    obj1.MyTeam = r["MyTeam"].ToString();
                    obj1.DirectSponsor = r["DirectSponsor"].ToString();
                    obj1.Amount = r["Amount"].ToString();
                    obj1.ForDays = r["ForDays"].ToString();
                    obj1.SingleLegStatus = r["Status"].ToString();
                    list1.Add(obj1);
                }
                model.SingleLegDashboardList = list1;
            }
            return View(model);
        }

        public ActionResult GetStateCityByPincode(string PinCode)
        {
            Associate model = new Associate();
            try
            {

                model.PinCode = PinCode;



                DataSet ds = model.GetStateCityByPincode();

                if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
                {

                    model.State = ds.Tables[0].Rows[0]["StateName"].ToString();
                    model.City = ds.Tables[0].Rows[0]["CityName"].ToString();
                    model.Result = "Yes";
                }

            }
            catch (Exception ex)
            {

            }
            return Json(model, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ViewProfile(Associate model)
        {
            model.Fk_UserId = Session["Pk_userId"].ToString();
            DataSet ds = model.GettingProfile();
            if (ds != null && ds.Tables.Count > 0)
            {
                model.ProductName = ds.Tables[0].Rows[0]["ProductName"].ToString();
                model.LoginId = ds.Tables[0].Rows[0]["LoginId"].ToString();
                model.Name = ds.Tables[0].Rows[0]["Name"].ToString();
                model.Mobile = ds.Tables[0].Rows[0]["Mobile"].ToString();
                model.SponsorID = ds.Tables[0].Rows[0]["SponsorId"].ToString();
                model.SponsorName = ds.Tables[0].Rows[0]["SponsorName"].ToString();
                model.BankName = ds.Tables[0].Rows[0]["BankName"].ToString();
                model.BankHolderName = ds.Tables[0].Rows[0]["BankHolderName"].ToString();
                model.AccountNo = ds.Tables[0].Rows[0]["AccountNo"].ToString();
                model.IFSC = ds.Tables[0].Rows[0]["IFSC"].ToString();
                model.BankBranch = ds.Tables[0].Rows[0]["BankBranch"].ToString();
                model.Address = ds.Tables[0].Rows[0]["Address"].ToString();
                model.PinCode = ds.Tables[0].Rows[0]["PinCode"].ToString();
                model.State = ds.Tables[0].Rows[0]["State"].ToString();
                model.City = ds.Tables[0].Rows[0]["City"].ToString();
                model.PanNumber = ds.Tables[0].Rows[0]["PanNumber"].ToString();
                model.PAYTMNo = ds.Tables[0].Rows[0]["PAYTMNo"].ToString();
                model.Phonepay = ds.Tables[0].Rows[0]["Phonepay"].ToString();
                model.GooglePay = ds.Tables[0].Rows[0]["GooglePay"].ToString();
                model.NomineName = ds.Tables[0].Rows[0]["NomineName"].ToString();
                model.NomineRealation = ds.Tables[0].Rows[0]["NomineRealation"].ToString();
            }
            return View(model);
        }


        public ActionResult UpdateProfile(Associate model, IEnumerable<HttpPostedFileBase> Image)
        {
            model.Fk_UserId = Session["Pk_userId"].ToString();
            DataSet ds = model.GettingProfile();
            if (ds != null && ds.Tables.Count > 0)
            {
                model.ProductName = ds.Tables[0].Rows[0]["ProductName"].ToString();
                model.LoginId = ds.Tables[0].Rows[0]["LoginId"].ToString();
                model.Name = ds.Tables[0].Rows[0]["Name"].ToString();
                model.Mobile = ds.Tables[0].Rows[0]["Mobile"].ToString();
                model.SponsorID = ds.Tables[0].Rows[0]["SponsorId"].ToString();
                model.SponsorName = ds.Tables[0].Rows[0]["SponsorName"].ToString();
                model.BankName = ds.Tables[0].Rows[0]["BankName"].ToString();
                model.BankHolderName = ds.Tables[0].Rows[0]["BankHolderName"].ToString();
                model.AccountNo = ds.Tables[0].Rows[0]["AccountNo"].ToString();
                model.IFSC = ds.Tables[0].Rows[0]["IFSC"].ToString();
                model.BankBranch = ds.Tables[0].Rows[0]["BankBranch"].ToString();
                model.Address = ds.Tables[0].Rows[0]["Address"].ToString();
                model.PinCode = ds.Tables[0].Rows[0]["PinCode"].ToString();
                model.State = ds.Tables[0].Rows[0]["State"].ToString();
                model.City = ds.Tables[0].Rows[0]["City"].ToString();
                model.PanNumber = ds.Tables[0].Rows[0]["PanNumber"].ToString();
                model.PAYTMNo = ds.Tables[0].Rows[0]["PAYTMNo"].ToString();
                model.Phonepay = ds.Tables[0].Rows[0]["Phonepay"].ToString();
                model.GooglePay = ds.Tables[0].Rows[0]["GooglePay"].ToString();
                model.NomineName = ds.Tables[0].Rows[0]["NomineName"].ToString();
                model.NomineRealation = ds.Tables[0].Rows[0]["NomineRealation"].ToString();
                model.DOB = ds.Tables[0].Rows[0]["DOB"].ToString();
                model.Email = ds.Tables[0].Rows[0]["Email"].ToString();
                model.ProfilePic = ds.Tables[0].Rows[0]["ProfilePic"].ToString();
            }



            return View(model);
        }

        [HttpPost]
        [OnAction(ButtonName = "btnUpdateProfile")]
        [ActionName("UpdateProfile")]
        public ActionResult UpdateUserProfile(Associate model, IEnumerable<HttpPostedFileBase> Image)
        {
            model.Fk_UserId = Session["Pk_userId"].ToString();
            model.UpdatedBy = Session["Pk_userId"].ToString();
            try
            {
                foreach (var file in Image)
                {
                    if (file != null && file.ContentLength > 0)
                    {

                        model.ProfilePic = "../AssociatePic/" + Guid.NewGuid() + Path.GetExtension(file.FileName);
                        file.SaveAs(Path.Combine(Server.MapPath(model.ProfilePic)));
                    }
                }
                model.DOB = string.IsNullOrEmpty(model.DOB) ? null : Common.ConvertToSystemDate(model.DOB, "dd/MM/yyyy");
                DataSet ds = model.UpdatingProfile();
                if (ds != null && ds.Tables.Count > 0)
                {
                    if (ds.Tables[0].Rows[0]["Msg"].ToString() == "1")
                    {

GYF/Views/Associate/ChangePasswordUser.cshtml
@model GYF.Models.Associate
@{
    ViewBag.Title = "ChangePasswordUser";
    Layout = "~/Views/Shared/AssociateLayout.cshtml";
}


@using (Html.BeginForm("ChangePasswordUser", "Associate", FormMethod.Post, new { @id = "signupForm" }))
{
           <!-- Page header -->
    <div class="page-header page-header-light">
        <div class="page-header-content header-elements-md-inline">
            <div class="page-title d-flex">
                <h4><i class="icon-arrow-left52 mr-2"></i> <span class="font-weight-semibold">Associate</span> - Change Password</h4>
                <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
            </div>
        </div>
    </div>
    <!-- /page header -->

    <div class="content">

        <div class="row">
            <div class="col-xl-12">
                <!-- Marketing campaigns -->
                <div class="card">
                    <div class="card-header header-elements-sm-inline">
                        <h6 class="card-title">Change Password</h6>

                    </div>
                    <div class="card-header">

                        <p style="color: red">
                            @TempData["Error"]
                        </p>
                    </div>
                    <div class="card-body">
                        <div class="row justify-content-center">
                            <div class="col-md-12 mx-auto">
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            Old Password<span style="color: red">*</span>
                                            @Html.PasswordFor(m => m.Password, new { @class = "form-control", @placeholder = "Old Password" })
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            New Password<span style="color: red">*</span>
                                            @Html.PasswordFor(m => m.NewPassword, new { @class = "form-control", @placeholder = "New Password" })

                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            Confirm Password<span style="color: red">*</span>
                                            @Html.PasswordFor(m => m.ConfirmNewPassword, new { @class = "form-control", @placeholder = "Confirm Password", @onchange = "return CheckConfirmPassword();" })
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <input class="btn btn-success pull-left" type="submit" value="Update" id="Update" name="Update" onclick="return validate();" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<script>

    function validate()
    {
        if ($('#Password').val() == '') {
            $("#Password").addClass('errortext');
            $('#Password').focus();
            return false;
        }
        if ($('#NewPassword').val() == '') {
            $("#NewPassword").addClass('errortext');
            $('#NewPassword').focus();
            return false;
        }
        if ($('#ConfirmNewPassword').val() == '') {
            $("#ConfirmNewPassword").addClass('errortext');
            $('#ConfirmNewPassword').focus();
            return false;
        }
    }


    function CheckConfirmPassword()
    {
        $(".errortext").removeClass("errortext");
        if($("#NewPassword").val()!=$("#ConfirmNewPassword").val())
        {
            alert("New Password and Confirm Password Should be same");
            $("#NewPassword").addClass("errortext");
            $("#ConfirmNewPassword").addClass("errortext");
            $("#NewPassword").val("");
            $("#ConfirmNewPassword").val("");
            $("#NewPassword").focus();
            $("#ConfirmNewPassword").focus();
        }
    }
</script>
<style>
    .errortext {
        border: 1px solid red !important;
        background-color: #fff0f0 !important;
    }
</style>

GYF/Views/Associate/DirectIncome.cshtml
@model GYF.Models.Associate

@{
    ViewBag.Title = "DirectIncome";
    Layout = "~/Views/Shared/AssociateLayout.cshtml";
}

@using (Html.BeginForm("DirectIncome", "Associate", FormMethod.Post, new { id = "form" }))
{

    <!-- Page header -->
    <div class="page-header page-header-light">
        <div class="page-header-content header-elements-md-inline">
            <div class="page-title d-flex">
                <h4><i class="icon-arrow-left52 mr-2"></i> <span class="font-weight-semibold">Income </span> - Direct Income</h4>
                <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
            </div>
        </div>
    </div>
    <!-- /page header -->

    <div class="content">

        <div class="row">
            <div class="col-xl-12">
                <!-- Marketing campaigns -->
                <div class="card">
                    <div class="card-header header-elements-sm-inline">
                        <h6 class="card-title">Direct Income</h6>

                    </div>
                    <div class="card-header">

                        <p style="color: red">
                            @TempData["DirectIncome"]
                        </p>
                    </div><div class="card-body">
                        <div class="row justify-content-center">
                            <div class="col-md-12 mx-auto">
                                <div class="row ">

                                    <div class="col-lg-3 col-md-3">
                                        <div class="form-group ">
                                            <label> From Date</label>
                                            @Html.TextBoxFor(m => m.FromDate, new { @class = "form-control", @readonly = "readonly" })

                                        </div>
                                    </div>
                                    <div class="col-lg-3 col-md-3">
                                        <div class="form-group ">
                                            <label> To Date </label>
                                            @Html.TextBoxFor(m => m.ToDate, new { @class = "form-control", @readonly = "readonly" })
                                        </div>
                                    </div>
                                    <div class="col-lg-3 col-md-3">
                                        <div class="form-group ">
                                            <input type="submit" class="btn btn-info" name="btnDetails" id="btnDetails" style="margin-top:25px" value="Get Details" />
                                        </div>
                                    </div>
                                </div>


                            </div>
                        </div>

                    </div>
                    <div class="table-responsive">
                        <table class="table table-bordered w-100 mb-0" id="example25">
                            <thead>
                                <tr>

                                    <th>Sr No.</th>
                                    <th>Date</th>
                                    <th>From Id</th>
                                    <th>Direct Income</th>
                                    <th>Status</th>

                                </tr>

                            </thead>
                            <tbody>
                                @if (Model != null)
                                {
                                    if (Model.DirectIncomeList != null)
                                    {
                                        int i = 1;
                                        foreach (var Item in Model.DirectIncomeList)
                                        {
                                            <tr class="text-left">

                                                <td>
                                                    @i

                                                </td>
                                                <td>@Item.CurrentDate</td>
                                                <td>@Item.FromId</td>
                                                <td>@Item.Amount</td>
                                                <td>@Item.Status</td>



                                            </tr>
                                            i++;
                                        }

                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

}

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<script>

    $('#FromDate').datepicker({
        dateFormat: 'dd/mm/yy',
        changeMonth: true,
        changeYear: true,
        yearRange: '1950:2020'
    });

    $('#ToDate').datepicker({
        dateFormat: 'dd/mm/yy',
        changeMonth: true,
        changeYear: true,
        yearRange: '1950:2020'
    });
</script>

GYF/Views/Associate/DirectReport.cshtml
@model GYF.Models.Associate

@{
    ViewBag.Title = "DirectReport";
    Layout = "~/Views/Shared/AssociateLayout.cshtml";
}

@using (Html.BeginForm("DirectReport", "Associate", FormMethod.Post, new { @id = "form3", enctype = "multipart/form-data" }))
{
    <div class="page-header page-header-light">
        <div class="page-header-content header-elements-md-inline">
            <div class="page-title d-flex">
                <h4><i class="icon-arrow-left52 mr-2"></i> <span class="font-weight-semibold">Team </span> - Direct</h4>
                <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
            </div>
        </div>
    </div>
    <!-- /page header -->

    <div class="content">

        <div class="row">
            <div class="col-xl-12">
                <!-- Marketing campaigns -->
                <div class="card">
                    <div class="card-header header-elements-sm-inline">
                        <h6 class="card-title">Direct</h6>
                        <p style="color:red">
                            @TempData["DirectReport"]
                        </p>
                    </div>

                    <div class="table-responsive">
                        <table class="table table-bordered w-100 mb-0" id="example25">
                            <thead>
                                <tr>

                                    <th>Sr No.</th>
                                    <th>Login Id</th>
                                    <th>Name</th>
                                    <th>Joining Date</th>
                                    <th>Active Date</th>
                                    <th>Mobile</th>

                                </tr>

                            </thead>
                            <tbody>
                                @if (Model != null)
                                {
                                    if (Model.DirectReportList != null)
                                    {
                                        int i = 1;
                                        foreach (var Item in Model.DirectReportList)
                                        {
                                            <tr class="text-left">

                                                <td>
                                                    @i
                                                </td>
                                                <td>@Item.LoginId</td>
                                                <td>@Item.Name</td>
                                                <td>@Item.JoiningDate</td>
                                                <td>@Item.PermanentDate</td>
                                                <td>@Item.Mobile</td>

                                            </tr>
                                            i++;
                                        }

                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

}

GYF/Views/Associate/PayoutRequest.cshtml
@model GYF.Models.Associate
@{
    ViewBag.Title = "PayoutRequest";
    Layout = "~/Views/Shared/AssociateLayout.cshtml";
}
@using (Html.BeginForm("PayoutRequest", "Associate", FormMethod.Post, new { id = "form" }))
{

    <!-- Page header -->
    <div class="page-header page-header-light">
        <div class="page-header-content header-elements-md-inline">
            <div class="page-title d-flex">
                <h4><i class="icon-arrow-left52 mr-2"></i> <span class="font-weight-semibold">Payout Wallet</span> - Payout Request</h4>
                <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
            </div>
        </div>
    </div>
    <!-- /page header -->

    <div class="content">
        <div class="row">
            <div class="col-xl-12">
                <!-- Marketing campaigns -->
                <div class="card">
                    <div class="card-header header-elements-sm-inline">
                        <h6 class="card-title">Payout Request</h6>

                    </div>
                    <div class="card-header">

                        <p style="color: red">
                            @TempData["PayoutRequest"]
                        </p>
                    </div>
                    <div class="card-body">
                        <div class="row justify-content-center">
                            <div class="col-md-12 mx-auto">
                                <span style="color:red;"><b>Wallet Amount  : @ViewBag.PayoutWallet</b> </span>
                                <div class="row ">
                                    <div class="col-lg-3 col-md-3">
                                        <div class="form-group">
                                            <label>
                                                Login Id
                                            </label>
                                            @Html.TextBoxFor(m => m.LoginId, new { @class = "form-control", @Placeholder = "Login Id", @disabled="true"})

                                        </div>
                                    </div>
                                    <div class="col-lg-3 col-md-3">
                                        <div class="form-group">
                                            <label>Amount</label>
                                            @Html.TextBoxFor(m => m.Amount, new { @class = "form-control", @Placeholder = "Amount", @onkeypress = "return isNumberOrDecimal(event);"} )

                                        </div>
                                    </div>
                                    <div class="col-lg-3 col-md-3">
                                        <div class="form-group ">
                                            <input type="submit" class="btn btn-info" name="btnsave" id="btnsave" style="margin-top:25px" value="Save" onclick="return ValidateForm();" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

}
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>

    function ValidateForm()
    {
        $(".errortext").removeClass("errortext")
        if ($("#Amount").val() === "") {
            $("#Amount").addClass("errortext");
            $("#Amount").focus();
            return false;

        }
        if ($("#LoginId").val() === "") {
            $("#LoginId").addClass("errortext");
            $("#LoginId").focus();
            return false;

        }
    }

    function isNumberOrDecimal(evt) {
        var charCode = (evt.which) ? evt.which : evt.keyCode;
        if (charCode != 46 && charCode > 31
          && (charCode < 48 || charCode > 57))
            return false;

        return true;
    }
</script>
<style>
    .errortext {
        border: 1px solid red !important;
        background-color: #fff0f0 !important;
    }
</style>
  

GYF/Views/Associate/Reward.cshtml
@model GYF.Models.Associate

@{
    ViewBag.Title = "Reward";
    Layout = "~/Views/Shared/AssociateLayout.cshtml";
}
@using (Html.BeginForm("Reward", "Associate", FormMethod.Post, new { @id = "form3", enctype = "multipart/form-data" }))
{
    <div class="page-header page-header-light">
        <div class="page-header-content header-elements-md-inline">
            <div class="page-title d-flex">
                <h4><i class="icon-arrow-left52 mr-2"></i> <span class="font-weight-semibold">Reward </span> </h4>
                <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
            </div>
        </div>
    </div>
    <!-- /page header -->

    <div class="content">

        <div class="row">
            <div class="col-xl-12">
                <!-- Marketing campaigns -->
                <div class="card">
                    <div class="card-header header-elements-sm-inline">
                        <h6 class="card-title">Reward</h6>
                        <p style="color:red">
                            @TempData["Reward"]
                        </p>
                    </div>
                   
                    <div class="table-responsive">
                        <table class="table table-bordered w-100 mb-0" id="example25">
                            <thead>
                                <tr>

                                    <th>Sr No.</th>
                                    <th>Target Level</th>
                                    <th>Reward</th>
                                    <th>Reward Image</th>
                                    <th>Status</th>
                                </tr>

                            </thead>
                            <tbody>
                                @if (Model != null)
                                {
                                    if (Model.Rewardlist != null)
                                    {
                                        int i = 1;
                                        foreach (var Item in Model.Rewardlist)
                                        {
                                            <tr class="text-left">

                                                <td>
                                                    @i
                                                </td>
                                                <td>@Item.TargetLevel</td>
                                                @*<td>@Item.TargetDirect</td>
                                                <td>@Item.TargetDays</td>*@
                                                <td>@Item.RewardAmount</td>
                                                <td>
                                                @if (Item.RewardImage != "")
                                                {
                                                    <img src="@Item.RewardImage" height="100" width="100" />
                                                }
                                                </td>
                                                <td>@Item.Status</td>
                                            </tr>
                                            i++;
                                        }

                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
        </div>
    </div>

}